### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by demoix** [MHLoppy/CBP-Launcher#2]
When I try to open launcher 0.2 it gives an error:

Error creating paths: System.NullReferenceException: Object reference not set to an instance of an object.
at CBPLauncher.MainWindow..ctor()

Windows 10

**Comment by MHLoppy** [comment]
Another user (HnZ on the RoN Discord) has had the same error and in his case it seems to be caused by not having a registry entry for the game install (I don't actually know how it's possible to install the game without having the registry entry created though!). I expect your error has the same cause.

When (if) the UI gets updated I'll be including the ability to bypass the automatic install location detection with a user-inputted install path instead, which is the best way I can think of to resolve the issue without knowing how it actually happens. Development has become very sporadic because CBP has seen almost no public usage even after >6 months, so I can't give you even a rough time estimate of when when the launcher would reach v0.4~v0.6, or even that it will get there at all unfortunately.

If you're up for it, I'd be interested in:

1. An idea of how long ago you installed RoN in this OS.
2. Whether your Windows 10 install is a "fresh" or "native" install, or whether it's an upgrade from another OS (e.g. Windows 7, 8, or 8.1).
3. If you're comfortable doing a search in the Windows registry, whether you have any RoN-related result when you search the entire registry for "skybox" (if you get results not related to RoN, you may need to run the search multiple times).

Thanks for taking the time to test the launcher and report the problem! I had no way of knowing whether this was a common or isolated issue until now, but with two out of the now-five systems tripping this error, it might be the former.

**Comment by demoix** [comment]
All I could say I was recently fresh installed RON and decided to look for mods. This is what first comes into my sight so I decided to try. My windows are Win10 fresh installed. And nothing comes at the search regarding skybox. Hope this helps

**Comment by MHLoppy** [comment]
Hiya, I've got a test version that includes two attempts to resolve the issue, the second being the user inputting the path manually (which should hopefully be very reliable in the worst-case-scenario). I've tested this by inducing what I think is the root problem on my system and it seems to do the trick, but I'm interested in seeing if it works on your system as well.

I can't directly upload an exe here (and this is in such an unfinished state that I don't want to release it as a new version on the project's releases), but you can give it a shot by hijacking this discord download that I gave to someone else to test: https://cdn.discordapp.com/attachments/231176909948583937/856647027098517544/CBPLauncher.exe

This is a partial and very incomplete implementation of a mix of v3 and v4 features - although I don't think it'll break anything as such, I don't really recommend actually using this beyond testing that it does work. If it _does_ work though, then a proper release with the same fixes won't be too far off. Please note that because the v3/v4 stuff is not completed, it's still **not compatible** with an existing CBP install if you have one (the local copy; the workshop subscription itself is fine) .

**Comment by MHLoppy** [comment]
With the release of v0.4 (see #5 ), I'm fairly confident this issue is now resolved. Give a yell if I'm wrong!
